import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body className="bg-gray-50 text-gray-900 font-sans">
          <nav className="bg-white shadow-md p-4 flex justify-between items-center">
            <Link href="/" className="font-bold text-xl">
              WorkConnect
            </Link>
            <div className="space-x-4 flex items-center">
              <Link href="/freelancer" className="hover:underline">
                Freelancer
              </Link>
              <Link href="/employer" className="hover:underline">
                Employer
              </Link>

              {/* Authentication Buttons */}
              <SignedOut>
                <SignInButton>
                  <button className="mr-2 bg-gray-200 hover:bg-gray-300 rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </nav>

          <main className="p-6">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
